services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: ${POSTGRES_CONTAINER}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data

    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    name: ${NETWORK_NAME}